### ISSUE TITLE
I cannot build SL5 project

### ISSUE THREAD

**Issue by kerryjiang** [facebook-csharp-sdk/simple-json#22] opened 2012-04-21 07:30 UTC
It said:

D:\Kerry\Workshop\SimpleJson\src\SimpleJson\SimpleJson.cs(1715,47): error CS1729: 'System.Reflection.Emit.DynamicMethod' does not contain a constructor that takes 5 arguments
D:\Kerry\Workshop\SimpleJson\src\SimpleJson\SimpleJson.cs(1773,21): error CS1729: 'System.Reflection.Emit.DynamicMethod' does not contain a constructor that takes 5 arguments
D:\Kerry\Workshop\SimpleJson\src\SimpleJson\SimpleJson.cs(1774,21): error CS1729: 'System.Reflection.Emit.DynamicMethod' does not contain a constructor that takes 5 arguments

**Comment by prabirshrestha** [comment] 2012-04-21 07:35
try cleaning the solution and building it again.

**Comment by kerryjiang** [comment] 2012-04-21 07:39
Still doesn't work.

-----Original Message-----

**Comment by prabirshrestha** [comment] 2012-04-21 09:14
I randomly get the same error you get.

Make sure you don't have SimpleJson.cs file opened in the VS tab. close it and then clean all solution then build. It is an annoying bug in VS.

Or you can also use the build script

install node js, then execute `npm install -g jake`, then in command line type `jake build:sl5`

**Comment by prabirshrestha** [comment] 2012-09-10 01:42
closing. cannot reproduce.

**Closed as completed by prabirshrestha** 2012-09-10 01:42 UTC
